### ISSUE TITLE
Metadata returns as an empty object when it shouldn't

### ISSUE THREAD

**Issue by sawyerh** [dropmark/dropmark-gem#11]
@sskylar Do you remember why we're doing this? https://github.com/dropmark/dropmark-gem/blob/master/lib/dropmark/item.rb#L20-L23 — seems to be causing the following:

Let's say we have an item that looks like this:

```
{
  description: 'hello world',
  metadata: {
    location: 'Brooklyn'
    size: 1234
  },
  ...
}
```

When you run:

```
Dropmark::Item.save_existing(params[:id], {
   description: 'blah'
})
```

The response returns the item with an empty metadata object:

```
{
  description: 'blah',
  metadata: {},
  ...
}
```

However when you run:

```
Dropmark::Item.save_existing(params[:id], {
   metadata: {
     location: 'Boston'
     size: 1234
  }
})
```

The response returns the item with the metadata object as you'd expect:

```
{
  description: 'blah',
  metadata: {
    location: 'Boston'
    size: 1234
  },
  ...
}
```

**Comment by sskylar** [comment]
The reason is because Her uses a `metadata` attribute as well, its there to avoid conflicts.

If you comment that part out does it work? I suspect it only appears to return metadata in the last example because it was already set.

**Comment by sawyerh** [comment]
Yeah, commenting out those lines makes it work, just unsure if that breaks anything that was working before.

**Comment by sskylar** [comment]
It can go. Seems the only place we use Her metadata is on collections/search:

https://github.com/oakstudios/dropmark-web/blob/e19c83dfb775186799e14a5e9729899309824eca/app/controllers/index.rb#L220

Basically Her metadata = HTTP headers. For items we can just use `item._metadata` for that, as defined here:

https://github.com/dropmark/dropmark-gem/blob/master/lib/dropmark/item.rb#L20

In fact we may want to do that across the board for all models (or maybe `headers` instead of `_metadata`).
